<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260331211950 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE pudu_account (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              api_key VARCHAR(255) NOT NULL,
              api_secret VARCHAR(255) NOT NULL,
              api_host VARCHAR(255) NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE pudu_account_user (
              pudu_account_id INT NOT NULL,
              user_id INT NOT NULL,
              PRIMARY KEY (pudu_account_id, user_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_FAC5D9A15E475C61 ON pudu_account_user (pudu_account_id)');
        $this->addSql('CREATE INDEX IDX_FAC5D9A1A76ED395 ON pudu_account_user (user_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              pudu_account_user
            ADD
              CONSTRAINT FK_FAC5D9A15E475C61 FOREIGN KEY (pudu_account_id) REFERENCES pudu_account (id) ON DELETE CASCADE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              pudu_account_user
            ADD
              CONSTRAINT FK_FAC5D9A1A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pudu_account_user DROP CONSTRAINT FK_FAC5D9A15E475C61');
        $this->addSql('ALTER TABLE pudu_account_user DROP CONSTRAINT FK_FAC5D9A1A76ED395');
        $this->addSql('DROP TABLE pudu_account');
        $this->addSql('DROP TABLE pudu_account_user');
    }
}
