<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260331221046 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create pudu_account_log table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE pudu_account_log (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              method VARCHAR(8) NOT NULL,
              uri VARCHAR(255) NOT NULL,
              body JSON DEFAULT NULL,
              response_code INT DEFAULT NULL,
              response_body JSON DEFAULT NULL,
              executed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              pudu_account_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_DE0016C45E475C61 ON pudu_account_log (pudu_account_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              pudu_account_log
            ADD
              CONSTRAINT FK_DE0016C45E475C61 FOREIGN KEY (pudu_account_id) REFERENCES pudu_account (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE pudu_account_log DROP CONSTRAINT FK_DE0016C45E475C61');
        $this->addSql('DROP TABLE pudu_account_log');
    }
}
