<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260331235447 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'create robot_group and robot_in_group tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE robot_group (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              pudu_group_id VARCHAR(255) NOT NULL,
              group_name VARCHAR(255) NOT NULL,
              pudu_shop_id INT NOT NULL,
              pudu_shop_name VARCHAR(255) NOT NULL,
              pudu_account_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_D866E3D45E475C61 ON robot_group (pudu_account_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE robot_in_group (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              mac VARCHAR(255) NOT NULL,
              sn VARCHAR(255) NOT NULL,
              robot_name VARCHAR(255) NOT NULL,
              pudu_shop_id INT NOT NULL,
              pudu_shop_name VARCHAR(255) NOT NULL,
              robot_group_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_E422BFBA3D433C46 ON robot_in_group (robot_group_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              robot_group
            ADD
              CONSTRAINT FK_D866E3D45E475C61 FOREIGN KEY (pudu_account_id) REFERENCES pudu_account (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              robot_in_group
            ADD
              CONSTRAINT FK_E422BFBA3D433C46 FOREIGN KEY (robot_group_id) REFERENCES robot_group (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE robot_group DROP CONSTRAINT FK_D866E3D45E475C61');
        $this->addSql('ALTER TABLE robot_in_group DROP CONSTRAINT FK_E422BFBA3D433C46');
        $this->addSql('DROP TABLE robot_group');
        $this->addSql('DROP TABLE robot_in_group');
    }
}
